#!/bin/bash
#PBS -S /bin/bash
#PBS -j oe
#PBS -m ae
#PBS -N ssHMmit

EXE=slave_spin_hm.exe
EXEDIR=$HOME/.bin

INPUTFILE=INPUT.in
RANGEFILE=list_var

#EDIT THIS TO FIT YOUR NEEDS!!
##############################################################################
loop()
{
    VAR1=$1
    HERE=$PBS_O_WORKDIR
    DIR=$HERE/U$VAR1
    mkdir $DIR
    cd $DIR
    cp -vf ../$INPUTFILE ../parameters .
    sed -e '1 d' INPUT.in -e "2i $1" < $INPUTFILE >tmp_file;mv -vf tmp_file $INPUTFILE
    $EXEDIR/$EXE
    cp -vf parameters  $HERE/
}


#    Execute the run.  Do not run in the background.       #
############################################################
runloop()
{
    cd $PBS_O_WORKDIR
    while read VAR
    do
	loop $VAR
    done < $RANGEFILE
}



##########################################
# RUN JOB:
##########################################
echo ------------------------------------------------------
echo 'Job is running on node(s): '
cat  $PBS_NODEFILE
echo ------------------------------------------------------
echo WORKINFO:
echo PBS: qsub is running on   $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is   $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: current home directory is $PBS_O_HOME
echo ""
echo JOBINFO:
echo PBS: execution mode is    $PBS_ENVIRONMENT
echo PBS: job identifier is    $PBS_JOBID
echo PBS: job name is          $PBS_JOBNAME
echo ""
echo NODEINFO:
echo PBS: node file is         $PBS_NODEFILE
echo ------------------------------------------------------
runloop
